# Generated by Django 4.0.5 on 2022-06-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemploLucaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
